In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [9]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix 
matrix = torch.tensor([[2, 3], [5, 4]])
matrix

tensor([[2, 3],
        [5, 4]])

In [16]:
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

In [19]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],[1, 2, 3]],
                       [[2, 3, 4], [2, 3, 4]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[2, 3, 4],
         [2, 3, 4]]])

In [20]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([2, 2, 3])

In [23]:
# Create random tensor of size 8, 8
RAND_TENSOR = torch.rand(8, 8)
RAND_TENSOR

tensor([[0.8332, 0.3741, 0.8870, 0.6367, 0.8840, 0.7129, 0.3548, 0.3432],
        [0.8541, 0.0750, 0.9449, 0.5397, 0.2497, 0.4980, 0.1438, 0.0236],
        [0.2883, 0.3839, 0.0113, 0.2118, 0.3488, 0.2100, 0.7861, 0.4056],
        [0.9310, 0.0159, 0.0512, 0.8592, 0.4868, 0.5831, 0.9481, 0.7104],
        [0.5497, 0.7049, 0.0810, 0.0331, 0.5402, 0.9957, 0.8212, 0.3349],
        [0.7718, 0.8493, 0.1359, 0.7047, 0.5889, 0.8993, 0.5891, 0.2037],
        [0.8926, 0.4794, 0.9346, 0.6538, 0.8168, 0.4021, 0.9763, 0.2921],
        [0.8564, 0.4294, 0.4407, 0.8797, 0.2187, 0.2925, 0.0939, 0.3970]])